name = "testing"
main = "src/index.js"
compatibility_date = "2022-12-06"


[env.production]
name = "webfingerio-prod-new"
vars = { ENVIRONMENT = "production" }

kv_namespaces = [
    {binding = "webfingerio_prod_auth", id = "1c742b5f453d42f68cedcec2ff075cb9"},
    {binding = "webfingerio_prod_data", id = "a91e37828ff14d838fdab5e4b689520f"}
]

routes = [
  "webfinger.io/",
  "webfinger.io/favicon.ico",
  "webfinger.io/robots.txt",
  "webfinger.io/.well-known/*",
  "webfinger.io/apiv1/*",
]
